---
name: Build RPMs and SRPMs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build RPMs and SRPMs for EL${{ matrix.alma_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alma_version: [8, 9, 10]
    container:
      image: almalinux:${{ matrix.alma_version }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y hdf5-devel zstd-devel gcc make

      - name: Build srpm
        run: |
          make srpm

      - name: Build RPM
        run: |
          make rpm
