---
name: Build RPMs and SRPMs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build RPMs and SRPMs for EL${{ matrix.alma_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        alma_version: [8, 9, 10]
    container:
      image: almalinux:${{ matrix.alma_version }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install config-manager dnf plugin
        run: |
          dnf install -y 'dnf-command(config-manager)'

      - name: On EL8, enable PowerTools repository
        if: matrix.alma_version == '8'
        run: |
          dnf config-manager --set-enabled powertools

      - name: On newer EL versions, enable CRB repository
        if: matrix.alma_version != '8'
        run: |
          dnf config-manager --set-enabled crb

      - name: Enable EPEL repository
        run: |
          dnf install -y epel-release

      - name: Install dependencies
        run: |
          dnf install -y hdf5-devel libzstd-devel gcc make rpmdevtools

      - name: Build srpm
        run: |
          make srpm

      - name: Build rpm
        run: |
          make rpm
