---

name: Build and Publish RPM on Release
on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: EL${{ matrix.alma_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        alma_version: [8, 9, 10]
    container:
      image: almalinux:${{ matrix.alma_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build RPM and SRPM
        uses: ./.github/actions/build-rpm-and-srpm
        with:
          alma_version: ${{ matrix.alma_version }}

      - name: Upload rpms to release
        run: |
          gh release upload ${{ github.event.release.tag_name }} *.rpm --clobber
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload srpm to release
        run: |
          gh release upload ${{ github.event.release.tag_name }} *.src.rpm --clobber
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
